# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: cargo fmt && git diff --exit-code
      - name: Lint
        run: |
          rustup update
          rustup component add clippy
          cargo clippy -- -D warnings

  build-msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Toolchain
      run: rustup install 1.59.0

    - name: Build
      run: |
        cargo +1.59.0 build
        
  build-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Toolchain
      run: rustup update

    - name: Build
      run: cargo build